# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: peddecord-photo-api
  name: peddecord-photo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      run: peddecord-photo-api-exposed
  template:
    metadata:
      labels:
        run: peddecord-photo-api-exposed
    spec:
      containers:
        - image: chrispeddecord/api:latest
          name: peddecord-photo-api
          ports:
            - containerPort: 8080
              protocol: TCP

---
# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: peddecord-photo-api
  name: peddecord-photo-api
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: peddecord-photo-api-exposed
  type: NodePort
