apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - name: ${PROJECT_NAME}
          image: gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: "BASE_PATH"
              value: /api/v1/
            - name: "USE_GRAPHIQL"
              value: "false"
            - name: "DO_SPACE_KEY"
              valueFrom:
                secretKeyRef:
                  name: do-spaces
                  key: do-space-key
            - name: "DO_SPACE_SECRET"
              valueFrom:
                secretKeyRef:
                  name: do-spaces
                  key: do-space-secret
