kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
spec:
  selector:
    app: ${PROJECT_NAME}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - name: ${PROJECT_NAME}
          image: eu.gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: "DO_SPACE_KEY"
              valueFrom:
                secretKeyRef:
                  name: do_spaces
                  key: do_space_key
            - name: "DO_SPACE_SECRET"
              valueFrom:
                secretKeyRef:
                  name: do_spaces
                  key: do_space_secret
            - name: "TEST_KEY_PLEASE_IGNORE"
              valueFrom:
                secretKeyRef:
                  name: do_spaces
                  key: test_key
---
apiVersion: v1
kind: Secret
metadata:
  name: do_spaces
type: Opaque
data:
  do_space_key: ${DO_SPACE_KEY}
  do_space_secret: ${DO_SPACE_SECRET}
  test_key: ${ENV_SECRET}
