version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/cpeddecord/peddecord-photo-api
    steps:
      - checkout

      - run:
          name: build
          command: go build

      - run:
          name: kill-gopher
          command: |
            ssh -o "StrictHostKeyChecking no" root@138.197.7.35 "tmux kill-session -t gopher"

      - run:
          name: scp
          command: |
            scp -o "StrictHostKeyChecking no" ./peddecord-photo-api root@138.197.7.35:/var/www

      - run:
          name: run
          command: |
            ssh -o "StrictHostKeyChecking no" root@138.197.7.35 "tmux new-session -d -s gopher /var/www/peddecord-photo-api"
